{{- if and .Values.auth.masterKey (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flaggy.fullname" . }}
  labels: {{- include "flaggy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretKey }}: {{ .Values.auth.masterKey | quote }}
{{- end }}
